using System.Collections.Generic;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.EventSystems;
using Height1079.Core;
using Height1079.Night;

namespace Height1079.Runtime
{
    /// <summary>Builds the whole scene from code when the game starts: slope, camp, lighting, network manager, UI.
    /// Prefabs (player, night session) are generated by the editor bootstrap into Assets/Resources.</summary>
    public static class Bootstrap
    {
        public static HeightField Dem { get; private set; }
        public static string PlayerName = "Путник";

        /// <summary>A name the rest of the game can hold. Two things bite here and both are one line to prevent:
        /// <c>FixedString64Bytes</c> throws above 61 <b>bytes</b> while the menu field counts <b>characters</b>, so
        /// twenty-one Cyrillic letters plus an emoji used to throw inside OnNetworkSpawn — before the camera was
        /// made, leaving a null camera and an exception every frame; and the party packet is joined with ';' and
        /// '|', so a name containing either made every client's parse of it fail four times a second.</summary>
        public static string CleanName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "Путник";
            var clean = name.Trim().Replace(';', ' ').Replace('|', ' ').Replace('\n', ' ').Replace('\r', ' ');
            while (clean.Length > 0 && System.Text.Encoding.UTF8.GetByteCount(clean) > 60)
                clean = clean.Substring(0, clean.Length - 1);
            clean = clean.Trim();
            return clean.Length == 0 ? "Путник" : clean;
        }
        public static bool AutoKindle;
        /// <summary>HUD button: keep working with the axe or the saw (the same as holding E).</summary>
        public static bool AutoWork;
        /// <summary>Set by the optional Steam assembly; null when the game runs with plain Unity Transport.</summary>
        public static ILobbyProvider Lobby;
        public static HudController Hud { get; private set; }
        /// <summary>Our own hiker. Fifteen systems read this every frame — the HUD several times — so the component
        /// is looked up once per player object and then held: the property used to run GetComponent on every call.</summary>
        public static HikerController LocalHiker
        {
            get
            {
                var nm = NetworkManager.Singleton;
                var obj = nm != null && nm.LocalClient != null ? nm.LocalClient.PlayerObject : null;
                if (obj == null) { mineObject = null; mine = null; return null; }
                if (!ReferenceEquals(obj, mineObject) || mine == null)
                {
                    mineObject = obj;
                    mine = obj.GetComponent<HikerController>();
                }
                return mine;
            }
        }
        static NetworkObject mineObject;
        static HikerController mine;

        /// <summary>0 at dusk, 1 in full night: drives light, fog, film and the forest sounds.</summary>
        public static float Darkness { get; private set; }

        static Light sun;
        static Light fireLight;
        static Renderer ember;
        static ParticleSystem fireSmoke, flames;
        static NetworkManager network;

        /// <summary>Name of the physics sandbox scene. It has no world, no network and no night: the body is the only
        /// thing in it, so the game must keep its hands off (Assets/Scripts/Sandbox).</summary>
        public const string SandboxScene = "Sandbox";

        /// <summary>Loads the physics sandbox. Everything the game put in DontDestroyOnLoad is taken down by the
        /// sandbox itself; coming back, <see cref="Boot"/> runs again (see <see cref="OnSceneLoaded"/>).</summary>
        public static void OpenSandbox() => SceneManager.LoadScene(SandboxScene);

        /// <summary>`1079 -sandbox` opens the physics sandbox straight away, without the menu — the short way in
        /// while the body is being worked on.</summary>
        static bool SandboxAsked
        {
            get
            {
                foreach (var a in System.Environment.GetCommandLineArgs()) if (a == "-sandbox") return true;
                return false;
            }
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Boot()
        {
            if (SceneManager.GetActiveScene().name == SandboxScene) return;
            if (Object.FindFirstObjectByType<NetworkManager>() != null) return;
            // a second Boot (back from the sandbox) starts from nothing: the old roots died with the scene, and the
            // lists still holding their corpses would stop SetPlace from ever rebuilding the mountain
            placeObjects.Clear(); placeExtras.Clear();
            SceneManager.sceneLoaded -= OnSceneLoaded;
            SceneManager.sceneLoaded += OnSceneLoaded;
            if (SandboxAsked) { OpenSandbox(); return; }
            // every knob that trades looks for frames, remembered between runs (Quality). It used to be two lines of
            // Mathf.Max here, which meant the game could raise the machine's quality level but never lower it.
            Quality.Apply();
            LoadPlace();
            BuildNetwork();
            Hud = HudController.Create();
            Ambience.Create();
            Weather.Create().gameObject.AddComponent<WeatherDriver>();
            PackView.Create();
            CampView.Create();
            var driver = new GameObject("Atmosphere", typeof(Atmosphere));
            Object.DontDestroyOnLoad(driver);
            atmosphere = driver.GetComponent<Atmosphere>();
        }

        /// <summary>Back from the sandbox the whole game has to be built again — the sandbox destroys what Boot put
        /// in DontDestroyOnLoad, including the network manager Boot checks for.</summary>
        static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (scene.name == SandboxScene || Object.FindFirstObjectByType<NetworkManager>() != null) return;
            Boot();
        }

        /// <summary>Root objects the world build created, so switching places can take them down again.</summary>
        static readonly List<GameObject> placeObjects = new List<GameObject>();
        static readonly List<GameObject> placeExtras = new List<GameObject>();

        /// <summary>Menu: the chosen place. Everything — terrain, height grid, dressing, light, weather helpers — is rebuilt,
        /// because the two maps have different sizes, frames and rules; without this the hiker spawns outside the terrain.</summary>
        public static void SetPlace(Place place)
        {
            if (place == World.Current && placeObjects.Count > 0) return;
            if (NetworkManager.Singleton != null && (NetworkManager.Singleton.IsListening || NetworkManager.Singleton.IsConnectedClient)) return;
            // the height grid first. Loading it is the one step here that can fail — a world the editor never
            // generated — and it used to be taken after the old place had already been torn down and World.Current
            // moved, which left the new mountain standing on the old one's heights.
            var was = World.Current;
            World.Current = place;
            HeightField dem;
            try { dem = TerrainBuilder.LoadDem(); }
            catch (System.IO.FileNotFoundException e)
            {
                World.Current = was;
                Debug.LogError("1079: " + e.Message);
                return;
            }
            foreach (var go in placeObjects) if (go != null) Object.Destroy(go);
            placeObjects.Clear();
            foreach (var go in placeExtras) if (go != null) Object.Destroy(go);
            placeExtras.Clear();
            Forest.Forget();
            LoadPlace(dem);
        }

        /// <summary>Loads the height grid of the active place, builds its world and points the menu camera at it.</summary>
        static void LoadPlace(HeightField loaded = null)
        {
            Dem = loaded ?? TerrainBuilder.LoadDem();
            // shadows, grass and per-pixel lights are set per place: six pixel lights is a night number, and the day
            // was paying for it (Quality)
            Quality.Apply();
            var before = new HashSet<GameObject>(SceneManager.GetActiveScene().GetRootGameObjects());
            BuildWorld();
            foreach (var go in SceneManager.GetActiveScene().GetRootGameObjects())
                if (!before.Contains(go)) placeObjects.Add(go);
            // the night machinery belongs to Kholat only
            if (!World.IsElbrus)
            {
                placeExtras.Add(SnowFx.Create().gameObject);
                placeExtras.Add(SkiTrailFx.Create().gameObject);
                placeExtras.Add(ForestMist.Create().gameObject);
                placeExtras.Add(MenkView.Create().gameObject);
            }
            atmosphere?.ApplyPlace();
            PlaceMenuCamera();
        }

        static Atmosphere atmosphere;

        /// <summary>The menu looks up the valley from behind the 31 Jan camp toward the slope; the scene camera in Main.unity sits inside the mountain otherwise.</summary>
        static void PlaceMenuCamera()
        {
            var cam = Camera.main; if (cam == null) return;
            Scenery.Cull(cam);
            if (World.IsElbrus)
            {
                var a = Elbrus.Azau; var top = Elbrus.WestSummit;
                float ay = Dem.Sample(a.X, a.Z) + 60f;
                cam.transform.position = new Vector3(a.X + 120f, ay, a.Z - 260f);
                cam.transform.LookAt(new Vector3(top.X, Dem.Sample(top.X, top.Z), top.Z));
                cam.nearClipPlane = .1f; cam.farClipPlane = 20000f;
                return;
            }
            var (cx, cz) = WorldData.Camp;
            float y = TerrainBuilder.Height(Dem, cx, cz) + 28f;
            // behind the camp, looking up the ascent toward the tent
            var away = new Vector3(cx - WorldData.Tent.X, 0, cz - WorldData.Tent.Z).normalized;
            cam.transform.position = new Vector3(cx, y, cz) + away * 45f;
            cam.transform.LookAt(new Vector3(WorldData.Tent.X, TerrainBuilder.Height(Dem, WorldData.Tent.X, WorldData.Tent.Z), WorldData.Tent.Z));
            cam.nearClipPlane = .1f; cam.farClipPlane = 4500f;
        }

        static Material Flat(Color c)
        {
            var template = Resources.Load<Material>("Flat"); // created by ProjectSetup so the shader ships in builds
            var m = template != null ? new Material(template) { color = c } : new Material(Shader.Find("Standard")) { color = c };
            m.SetFloat("_Glossiness", .05f); m.SetFloat("_Metallic", 0f);
            return m;
        }

        static void BuildWorld()
        {
            TerrainBuilder.Build();
            if (World.IsElbrus) { BuildElbrus(); return; }
            WorldDressing.Build(Dem);

            var sunGo = new GameObject("Sun", typeof(Light));
            sun = sunGo.GetComponent<Light>();
            sun.type = LightType.Directional; sun.color = new Color(1f, .94f, .84f); sun.intensity = 1.6f; sun.shadows = LightShadows.Soft;
            // Late afternoon of 1 Feb at 61.8° N: low sun in the south-west, light travelling north-east.
            sunGo.transform.rotation = Quaternion.Euler(14f, 55f, 0f);
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(.89f, .94f, 1f); RenderSettings.ambientEquatorColor = new Color(.6f, .66f, .7f); RenderSettings.ambientGroundColor = new Color(.35f, .38f, .4f);
            RenderSettings.fog = true; RenderSettings.fogMode = FogMode.ExponentialSquared; RenderSettings.fogDensity = .0013f; RenderSettings.fogColor = new Color(.68f, .74f, .78f);

            // Night camp of 31 Jan: burning stack on the log raft of Site_Camp_31Jan_Fire, ember, fire light.
            var camp = new GameObject("Camp");
            float cx = WorldData.Camp.x, cz = WorldData.Camp.z, cy = TerrainBuilder.Height(Dem, cx, cz);
            camp.transform.position = new Vector3(cx, cy, cz);
            // the half-burnt stack and the embers are part of Site_Camp_31Jan_Fire; the flames are particles
            var emberPart = GameObject.Find("Site_Camp_31Jan_Fire(Clone)/Embers") ?? GameObject.Find("Embers");
            ember = emberPart != null ? emberPart.GetComponent<Renderer>() : null;
            if (ember != null) ember.enabled = false;
            flames = CampSmoke.CreateFlames(camp.transform, new Vector3(0, .22f, 0));
            var lightGo = new GameObject("FireLight", typeof(Light)); lightGo.transform.SetParent(camp.transform, false); lightGo.transform.localPosition = new Vector3(0, .9f, 0);
            fireLight = lightGo.GetComponent<Light>(); fireLight.type = LightType.Point; fireLight.color = new Color(1f, .64f, .28f); fireLight.range = 24f; fireLight.intensity = 0f; fireLight.shadows = LightShadows.Soft;
            fireSmoke = CampSmoke.Create("FireSmoke", camp.transform, new Vector3(0, .9f, 0), 6f, 1.1f, .9f);
            var pipe = GameObject.Find("StovePipeSmoke");
            if (pipe != null) CampSmoke.Create("StoveSmoke", pipe.transform, Vector3.zero, 7f, .7f, .7f);
            else Debug.LogWarning("1079: StovePipeSmoke anchor not found");
        }

        /// <summary>The southern slope of Elbrus: ropeways, the Garabashi camp and the summit route, in daylight.
        /// None of the 1959 dressing applies here — no camp fire, no archive layer, no night.</summary>
        static void BuildElbrus()
        {
            var sunGo = new GameObject("Sun", typeof(Light));
            sun = sunGo.GetComponent<Light>();
            sun.type = LightType.Directional;
            ElbrusWorld.Daylight(sun);
            ElbrusWorld.Build(Dem);
        }

        static void BuildNetwork()
        {
            var go = new GameObject("NetworkManager", typeof(NetworkManager), typeof(UnityTransport));
            Object.DontDestroyOnLoad(go);
            network = go.GetComponent<NetworkManager>();
            var transport = go.GetComponent<UnityTransport>();
            network.NetworkConfig = new NetworkConfig { NetworkTransport = transport, ConnectionApproval = false, EnableSceneManagement = false, TickRate = 30 };
            var player = Resources.Load<GameObject>("Hiker");
            var session = Resources.Load<GameObject>("NightSession");
            if (player == null || session == null) { Debug.LogError("Missing Resources/Hiker or Resources/NightSession prefab — open the project in the editor once (menu 1079 → Generate prefabs)."); return; }
            network.NetworkConfig.PlayerPrefab = player;
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = player });
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = session });
            network.OnServerStarted += () => Object.Instantiate(session).GetComponent<NetworkObject>().Spawn();
            network.OnClientDisconnectCallback += id => { if (id == network.LocalClientId || !network.IsListening) OnLeft(); };
        }

        public static void Host(string name)
        {
            PlayerName = CleanName(name);
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData("0.0.0.0", 7777, "0.0.0.0");
            if (network.StartHost()) Hud.ShowMenu(false); else Hud.SetStatus("Не удалось открыть порт 7777.");
        }

        /// <summary>«Продолжить»: pick up the newest save of the place chosen in the menu and host from it. The place
        /// is applied first (it rebuilds the whole world), then the save is parked in <see cref="Saves.Pending"/>,
        /// where the host's <see cref="NightSession"/> takes it as it spawns and puts the clock, the weather and the
        /// tent back before anybody is placed.</summary>
        public static void Continue(string name)
        {
            var slot = Saves.Newest(World.Current);
            if (slot.IsEmpty) { Hud.SetStatus("Сохранения для этого места нет."); return; }
            var save = Saves.Read(slot.Path);
            if (save == null) { Hud.SetStatus("Сейв не читается. Начните новый подъём."); return; }
            SetPlace(save.Place);
            Saves.Hold(save);
            Host(name);
            if (NetworkManager.Singleton != null && NetworkManager.Singleton.IsListening)
                Hud.SetStatus($"Продолжаем: {save.Where}, {Height1079.Core.AscentRoute.Clock(save.Hour)}.");
            else Saves.Forget();
        }

        public static void Join(string name, string address)
        {
            PlayerName = CleanName(name);
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData(string.IsNullOrWhiteSpace(address) ? "127.0.0.1" : address.Trim(), 7777);
            if (network.StartClient()) { Hud.ShowMenu(false); Hud.SetStatus("Подключаемся…"); } else Hud.SetStatus("Не удалось подключиться.");
        }

        public static void Leave()
        {
            Lobby?.Leave();
            if (network.IsListening) network.Shutdown();
            OnLeft();
        }

        static void OnLeft()
        {
            AutoKindle = false;
            // a save that was picked but never applied must not leak into the next session
            Saves.Forget();
            Cursor.lockState = CursorLockMode.None; Cursor.visible = true;
            if (Hud != null) { Hud.ShowMenu(true); Hud.SetStatus("Ночь закончена. Можно начать новую."); }
        }

        public static bool PointerOverUi() => EventSystem.current != null && EventSystem.current.IsPointerOverGameObject();

        /// <summary>Per-frame environment: sky darkens with the night, fog thickens in storms, the fire glows while it burns.</summary>
        sealed class Atmosphere : MonoBehaviour
        {
            // Light follows the real sky of 1 Feb 1959 (SkyDome): the sun set at 16:58, the game starts in civil twilight at 17:40,
            // nautical dusk ends 18:49, full night from 19:41; the waning moon rises at 04:21. No direct sunlight during the night.
            static readonly Color DuskAmbSky = new Color(.78f, .84f, .95f), DuskAmbEq = new Color(.52f, .56f, .64f), DuskAmbGround = new Color(.32f, .35f, .4f);
            static readonly Color NightAmbSky = new Color(.055f, .07f, .1f), NightAmbEq = new Color(.032f, .04f, .058f), NightAmbGround = new Color(.022f, .026f, .036f);

            NightFilm film;
            Light moonLight;

            static readonly int GhostNightId = Shader.PropertyToID("_GhostNight");

            void Start()
            {
                film = NightFilm.Create();
                ApplyPlace();
            }

            /// <summary>The hour the dome shows: the night the session is counting, or — when the demo reel is
            /// driving — whatever hour the reel wants. The dome itself knows nothing of either (it lives in the
            /// shared assembly now, <see cref="SkyDome"/>), so the game hands it this.</summary>
            static SkyMoment GameSky()
            {
                var s = NightSession.Instance;
                var now = SkyMoment.InNight(s != null ? s.Elapsed.Value : 0f);
                now.Running = s != null;
                // the demo reel walks the night itself, with no session behind it
                if (DemoReel.NightSeconds >= 0f) { now.NightSeconds = DemoReel.NightSeconds; now.Running = true; }
                if (DemoReel.ClockMinutes >= 0f) now.Minutes = DemoReel.ClockMinutes;
                return now;
            }

            /// <summary>The 1959 night sky and its moonlight exist on Kholat only; switching places takes them down or puts them back.</summary>
            public void ApplyPlace()
            {
                // whoever loaded this scene last owns the sky's clock: coming back from the small map, the game
                // takes it again here, before the dome is built
                SkyDome.Clock = GameSky;
                var dome = FindFirstObjectByType<SkyDome>();
                if (Height1079.Core.World.IsElbrus)
                {
                    if (dome != null) Destroy(dome.gameObject);
                    if (moonLight != null) { Destroy(moonLight.gameObject); moonLight = null; }
                    return;
                }
                if (dome == null) SkyDome.Create();
                if (moonLight != null) return;
                var go = new GameObject("MoonLight", typeof(Light));
                DontDestroyOnLoad(go);
                moonLight = go.GetComponent<Light>();
                moonLight.type = LightType.Directional; moonLight.color = new Color(.62f, .7f, .92f); moonLight.intensity = 0f; moonLight.shadows = LightShadows.Soft; moonLight.shadowStrength = .6f;
                moonLight.enabled = false;
            }

            void Update()
            {
                if (Height1079.Core.World.IsElbrus) { ElbrusDay(); return; }
                if (Controls.Archive && Hud != null)
                    Hud.SetStatus(WorldDressing.ToggleArchive() ? "Архивный слой: версии, ориентиры КАН, линия следов и подъём от лабаза (F2 — скрыть)." : "");
                if (Controls.SiteView && Hud != null)
                {
                    WorldDressing.NextView();
                    Hud.SetStatus(WorldDressing.ViewIndex < 0 ? "" : $"Осмотр места: {WorldDressing.ViewName} (F3 — дальше)");
                    // started with -shots, every step of the viewer also writes the frame to Shots/ (SiteShot)
                    if (WorldDressing.ViewIndex >= 0) SiteShot.Grab(WorldDressing.ViewId);
                }
                var s = NightSession.Instance;
                float blizzard = Weather.Storm;
                // darkness by the sun under the horizon (and a bit more under a closed cloud deck)
                float alt = SkyDome.SunAlt;
                float night = SkyDome.Darkness;
                if (s == null) night = 0f;
                // site views are for looking at things: keep them readable
                if (WorldDressing.ViewIndex >= 0 && !WorldDressing.ViewKeepsDark) night = Mathf.Min(night, .35f);
                // `1079 -shots` is the book being printed, and the book is one day: the morning of 2 February 1959.
                // The clock is pinned to 11:20, when the sun stands 8° over the south-south-east — as high as it
                // ever gets here in February, low enough to rake the snow and throw the shadows long. The sky view
                // is the exception and keeps its own hour, 05:00, because a night sky is the whole subject there.
                if (SiteShot.Asked && WorldDressing.ViewIndex >= 0)
                {
                    DemoReel.ClockMinutes = WorldDressing.ViewKeepsDark ? 24 * 60 + 5 * 60 : 24 * 60 + 11 * 60 + 20;
                    if (!WorldDressing.ViewKeepsDark) night = 0f;
                }
                else if (SiteShot.Asked) DemoReel.ClockMinutes = -1f;
                Darkness = Mathf.MoveTowards(Darkness, night, Time.deltaTime * .5f);
                float d = Darkness;
                // the ghost layer flips between a dark drawing on sunlit snow and a faint glow in the dark; it is
                // the world that knows which, so it tells the shader rather than the shader guessing
                Shader.SetGlobalFloat(GhostNightId, d);

                // fog takes the colour of the horizon, so the far forest melts into the sky; in a blizzard it is the grey wall of snow
                RenderSettings.fogColor = SkyDome.Horizon;
                // clear dusk: long views; night: the dark eats everything past ~60 m; blizzard gusts: a few metres
                float fog = s == null ? .0013f : Mathf.Lerp(.003f, .016f, d);
                fog = Mathf.Lerp(fog, Mathf.Lerp(.05f, .12f, Weather.Gust), blizzard);
                // a clear morning for the book: haze that eats the far ridge sells nothing
                if (SiteShot.Asked && WorldDressing.ViewIndex >= 0 && !WorldDressing.ViewKeepsDark) fog = Mathf.Min(fog, .0011f);
                RenderSettings.fogDensity = fog;
                // ambient: the sky's own light, warmed by the afterglow while it lasts, greened a little by an aurora
                var glow = SkyDome.Glow * .12f * (1f - d);
                var aur = new Color(0f, .03f, .015f) * SkyDome.Aurora * (1f - SkyDome.CloudCover * .7f);
                RenderSettings.ambientSkyColor = Color.Lerp(DuskAmbSky, NightAmbSky, d) + glow + aur;
                RenderSettings.ambientEquatorColor = Color.Lerp(DuskAmbEq, NightAmbEq, d) + glow * 1.4f + aur;
                RenderSettings.ambientGroundColor = Color.Lerp(DuskAmbGround, NightAmbGround, d);
                var cam = Camera.main; if (cam != null) { cam.clearFlags = CameraClearFlags.SolidColor; cam.backgroundColor = SkyDome.Horizon; }
                if (sun != null)
                {
                    // above the horizon: the low sun itself; below: the afterglow as a soft light from the sun's side, gone by nautical dusk
                    var dir = SkyDome.SunDir;
                    var flat = new Vector3(dir.x, 0, dir.z).normalized;
                    float up = Mathf.Max(alt, 7f) * Mathf.Deg2Rad;
                    var from = (flat * Mathf.Cos(up) + Vector3.up * Mathf.Sin(up)).normalized;
                    sun.transform.rotation = Quaternion.LookRotation(-from);
                    float direct = Mathf.InverseLerp(-.5f, 3f, alt);
                    float after = Mathf.InverseLerp(-11f, -1f, alt) * .45f * (1f - SkyDome.CloudCover * .5f);
                    sun.intensity = Mathf.Max(direct * 1.3f, after) * (1f - blizzard * .6f);
                    sun.color = direct > .01f ? new Color(1f, .78f, .6f) : Color.Lerp(new Color(.55f, .6f, .85f), new Color(.95f, .6f, .5f), Mathf.InverseLerp(-8f, -1f, alt));
                    sun.shadows = direct > .01f ? LightShadows.Soft : LightShadows.None;
                    sun.enabled = sun.intensity > .005f;
                }
                if (moonLight != null)
                {
                    // the thin waning moon low in the south-east before dawn: faint, blue, long soft shadows
                    float m = s == null ? 0f : Mathf.InverseLerp(0f, 8f, SkyDome.MoonAlt) * SkyDome.MoonLit * (1f - SkyDome.CloudCover * .8f) * (1f - blizzard);
                    var md = SkyDome.MoonDir;
                    var mflat = new Vector3(md.x, 0, md.z).normalized;
                    float mup = Mathf.Max(SkyDome.MoonAlt, 4f) * Mathf.Deg2Rad;
                    moonLight.transform.rotation = Quaternion.LookRotation(-(mflat * Mathf.Cos(mup) + Vector3.up * Mathf.Sin(mup)));
                    moonLight.intensity = m * .22f;
                    moonLight.enabled = moonLight.intensity > .003f;
                }
                float fire = s != null ? s.FireRemaining.Value : 0f;
                if (ember != null) ember.enabled = fire > 0f;
                if (flames != null) { var fe = flames.emission; fe.enabled = fire > 0f; }
                if (fireSmoke != null) { var em = fireSmoke.emission; em.enabled = fire > 0f; }
                if (fireLight != null) fireLight.intensity = fire > 0f ? (3.2f + .8f * Mathf.PerlinNoise(Time.time * 6f, 0f)) * Mathf.Lerp(1f, 1.4f, d) : 0f;
                if (film != null) film.Set(s != null ? d : 0f, blizzard);
                // the night fog hides everything past ~150 m (a blizzard: far less): don't draw trees nobody can see
                var terrain = Terrain.activeTerrain;
                if (terrain != null)
                {
                    float far = s == null ? 1400f : Mathf.Lerp(Mathf.Lerp(1400f, 260f, d), 120f, blizzard);
                    if (Mathf.Abs(terrain.treeDistance - far) > 10f) terrain.treeDistance = far;
                }
            }

            /// <summary>A clear day on the southern slope: aerial perspective and nothing else.</summary>
            const float ClearFog = .00012f;
            static readonly Color ClearHaze = new Color(.66f, .76f, .88f), CloudHaze = new Color(.84f, .87f, .9f);

            /// <summary>Daylight on Elbrus: nothing of the night machinery runs, the film stays clean — but the sky of
            /// the day is a <em>rule</em> before it is a picture. When <see cref="AscentRoute.VisibilityM"/> says a
            /// party can see three hundred metres, the player has to be unable to see further either, or the mountain
            /// is lying to him in the one place it must not (docs/ELBRUS.md, «Как это вызывается из рантайма»).</summary>
            void ElbrusDay()
            {
                Darkness = 0f;
                if (film != null) film.Set(0f, 0f);
                var cam = Camera.main;
                if (cam != null && cam.farClipPlane < 15000f) cam.farClipPlane = 20000f;

                float vis = Height1079.Core.AscentRoute.VisibilityM(Climb.Sky(Weather.Storm));
                float want = vis >= 2000f ? ClearFog : Mathf.Clamp(1.2f / Mathf.Max(60f, vis), ClearFog, .025f);
                RenderSettings.fogDensity = Mathf.MoveTowards(RenderSettings.fogDensity, want, Time.deltaTime * .006f);
                RenderSettings.fogColor = Color.Lerp(ClearHaze, CloudHaze, Mathf.InverseLerp(2000f, 120f, vis));
            }
        }
    }
}
