using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using UnityEngine;
using UnityEngine.EventSystems;
using Height1079.Core;

namespace Height1079.Runtime
{
    /// <summary>Builds the whole scene from code when the game starts: slope, camp, lighting, network manager, UI.
    /// Prefabs (player, night session) are generated by the editor bootstrap into Assets/Resources.</summary>
    public static class Bootstrap
    {
        public static HeightField Dem { get; private set; }
        public static string PlayerName = "Путник";
        public static bool AutoKindle;
        /// <summary>HUD button: keep working with the axe or the saw (the same as holding E).</summary>
        public static bool AutoWork;
        /// <summary>Set by the optional Steam assembly; null when the game runs with plain Unity Transport.</summary>
        public static ILobbyProvider Lobby;
        public static HudController Hud { get; private set; }
        public static HikerController LocalHiker
        {
            get
            {
                var nm = NetworkManager.Singleton;
                if (nm == null || nm.LocalClient == null || nm.LocalClient.PlayerObject == null) return null;
                return nm.LocalClient.PlayerObject.GetComponent<HikerController>();
            }
        }

        /// <summary>0 at dusk, 1 in full night: drives light, fog, film and the forest sounds.</summary>
        public static float Darkness { get; private set; }

        static Light sun;
        static Light fireLight;
        static Renderer ember;
        static ParticleSystem fireSmoke, flames;
        static NetworkManager network;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Boot()
        {
            if (Object.FindFirstObjectByType<NetworkManager>() != null) return;
            Application.targetFrameRate = 120;
            // the night is lit by a handful of small lights (torches, fire, stove): keep them per-pixel with shadows close by
            QualitySettings.pixelLightCount = Mathf.Max(QualitySettings.pixelLightCount, 6);
            QualitySettings.shadowDistance = Mathf.Max(QualitySettings.shadowDistance, 45f);
            Dem = TerrainBuilder.LoadDem();
            BuildWorld();
            BuildNetwork();
            Hud = HudController.Create();
            PlaceMenuCamera();
            Ambience.Create();
            SnowFx.Create();
            Weather.Create();
            ForestMist.Create();
            MenkView.Create();
            PackView.Create();
            var driver = new GameObject("Atmosphere", typeof(Atmosphere));
            Object.DontDestroyOnLoad(driver);
        }

        /// <summary>The menu looks up the valley from behind the 31 Jan camp toward the slope; the scene camera in Main.unity sits inside the mountain otherwise.</summary>
        static void PlaceMenuCamera()
        {
            var cam = Camera.main; if (cam == null) return;
            var (cx, cz) = WorldData.Camp;
            float y = TerrainBuilder.Height(Dem, cx, cz) + 28f;
            // behind the camp, looking up the ascent toward the tent
            var away = new Vector3(cx - WorldData.Tent.X, 0, cz - WorldData.Tent.Z).normalized;
            cam.transform.position = new Vector3(cx, y, cz) + away * 45f;
            cam.transform.LookAt(new Vector3(WorldData.Tent.X, TerrainBuilder.Height(Dem, WorldData.Tent.X, WorldData.Tent.Z), WorldData.Tent.Z));
            cam.nearClipPlane = .1f; cam.farClipPlane = 4500f;
        }

        static Material Flat(Color c)
        {
            var template = Resources.Load<Material>("Flat"); // created by ProjectSetup so the shader ships in builds
            var m = template != null ? new Material(template) { color = c } : new Material(Shader.Find("Standard")) { color = c };
            m.SetFloat("_Glossiness", .05f); m.SetFloat("_Metallic", 0f);
            return m;
        }

        static void BuildWorld()
        {
            TerrainBuilder.Build();
            WorldDressing.Build(Dem);

            var sunGo = new GameObject("Sun", typeof(Light));
            sun = sunGo.GetComponent<Light>();
            sun.type = LightType.Directional; sun.color = new Color(1f, .94f, .84f); sun.intensity = 1.6f; sun.shadows = LightShadows.Soft;
            // Late afternoon of 1 Feb at 61.8° N: low sun in the south-west, light travelling north-east.
            sunGo.transform.rotation = Quaternion.Euler(14f, 55f, 0f);
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(.89f, .94f, 1f); RenderSettings.ambientEquatorColor = new Color(.6f, .66f, .7f); RenderSettings.ambientGroundColor = new Color(.35f, .38f, .4f);
            RenderSettings.fog = true; RenderSettings.fogMode = FogMode.ExponentialSquared; RenderSettings.fogDensity = .0013f; RenderSettings.fogColor = new Color(.68f, .74f, .78f);

            // Night camp of 31 Jan: burning stack on the log raft of Site_Camp_31Jan_Fire, ember, fire light.
            var camp = new GameObject("Camp");
            float cx = WorldData.Camp.x, cz = WorldData.Camp.z, cy = TerrainBuilder.Height(Dem, cx, cz);
            camp.transform.position = new Vector3(cx, cy, cz);
            // the half-burnt stack and the embers are part of Site_Camp_31Jan_Fire; the flames are particles
            var emberPart = GameObject.Find("Site_Camp_31Jan_Fire(Clone)/Embers") ?? GameObject.Find("Embers");
            ember = emberPart != null ? emberPart.GetComponent<Renderer>() : null;
            if (ember != null) ember.enabled = false;
            flames = CampSmoke.CreateFlames(camp.transform, new Vector3(0, .22f, 0));
            var lightGo = new GameObject("FireLight", typeof(Light)); lightGo.transform.SetParent(camp.transform, false); lightGo.transform.localPosition = new Vector3(0, .9f, 0);
            fireLight = lightGo.GetComponent<Light>(); fireLight.type = LightType.Point; fireLight.color = new Color(1f, .64f, .28f); fireLight.range = 24f; fireLight.intensity = 0f; fireLight.shadows = LightShadows.Soft;
            fireSmoke = CampSmoke.Create("FireSmoke", camp.transform, new Vector3(0, .9f, 0), 6f, 1.1f, .9f);
            var pipe = GameObject.Find("StovePipeSmoke");
            if (pipe != null) CampSmoke.Create("StoveSmoke", pipe.transform, Vector3.zero, 7f, .7f, .7f);
            else Debug.LogWarning("1079: StovePipeSmoke anchor not found");
        }

        static void BuildNetwork()
        {
            var go = new GameObject("NetworkManager", typeof(NetworkManager), typeof(UnityTransport));
            Object.DontDestroyOnLoad(go);
            network = go.GetComponent<NetworkManager>();
            var transport = go.GetComponent<UnityTransport>();
            network.NetworkConfig = new NetworkConfig { NetworkTransport = transport, ConnectionApproval = false, EnableSceneManagement = false, TickRate = 30 };
            var player = Resources.Load<GameObject>("Hiker");
            var session = Resources.Load<GameObject>("NightSession");
            if (player == null || session == null) { Debug.LogError("Missing Resources/Hiker or Resources/NightSession prefab — open the project in the editor once (menu 1079 → Generate prefabs)."); return; }
            network.NetworkConfig.PlayerPrefab = player;
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = player });
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = session });
            network.OnServerStarted += () => Object.Instantiate(session).GetComponent<NetworkObject>().Spawn();
            network.OnClientDisconnectCallback += id => { if (id == network.LocalClientId || !network.IsListening) OnLeft(); };
        }

        public static void Host(string name)
        {
            PlayerName = string.IsNullOrWhiteSpace(name) ? "Путник" : name.Trim();
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData("0.0.0.0", 7777, "0.0.0.0");
            if (network.StartHost()) Hud.ShowMenu(false); else Hud.SetStatus("Не удалось открыть порт 7777.");
        }

        public static void Join(string name, string address)
        {
            PlayerName = string.IsNullOrWhiteSpace(name) ? "Путник" : name.Trim();
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData(string.IsNullOrWhiteSpace(address) ? "127.0.0.1" : address.Trim(), 7777);
            if (network.StartClient()) { Hud.ShowMenu(false); Hud.SetStatus("Подключаемся…"); } else Hud.SetStatus("Не удалось подключиться.");
        }

        public static void Leave()
        {
            Lobby?.Leave();
            if (network.IsListening) network.Shutdown();
            OnLeft();
        }

        static void OnLeft()
        {
            AutoKindle = false;
            Cursor.lockState = CursorLockMode.None; Cursor.visible = true;
            if (Hud != null) { Hud.ShowMenu(true); Hud.SetStatus("Ночь закончена. Можно начать новую."); }
        }

        public static bool PointerOverUi() => EventSystem.current != null && EventSystem.current.IsPointerOverGameObject();

        /// <summary>Per-frame environment: sky darkens with the night, fog thickens in storms, the fire glows while it burns.</summary>
        sealed class Atmosphere : MonoBehaviour
        {
            // Light follows the real sky of 1 Feb 1959 (SkyDome): the sun set at 16:58, the game starts in civil twilight at 17:40,
            // nautical dusk ends 18:49, full night from 19:41; the waning moon rises at 04:21. No direct sunlight during the night.
            static readonly Color DuskAmbSky = new Color(.78f, .84f, .95f), DuskAmbEq = new Color(.52f, .56f, .64f), DuskAmbGround = new Color(.32f, .35f, .4f);
            static readonly Color NightAmbSky = new Color(.055f, .07f, .1f), NightAmbEq = new Color(.032f, .04f, .058f), NightAmbGround = new Color(.022f, .026f, .036f);

            NightFilm film;
            Light moonLight;

            void Start()
            {
                film = NightFilm.Create();
                SkyDome.Create();
                var go = new GameObject("MoonLight", typeof(Light));
                DontDestroyOnLoad(go);
                moonLight = go.GetComponent<Light>();
                moonLight.type = LightType.Directional; moonLight.color = new Color(.62f, .7f, .92f); moonLight.intensity = 0f; moonLight.shadows = LightShadows.Soft; moonLight.shadowStrength = .6f;
                moonLight.enabled = false;
            }

            void Update()
            {
                if (Controls.Archive && Hud != null)
                    Hud.SetStatus(WorldDressing.ToggleArchive() ? "Архивный слой: версии, ориентиры КАН, линия следов и подъём от лабаза (F2 — скрыть)." : "");
                if (Controls.SiteView && Hud != null)
                {
                    WorldDressing.NextView();
                    Hud.SetStatus(WorldDressing.ViewIndex < 0 ? "" : $"Осмотр места: {WorldDressing.ViewName} (F3 — дальше)");
                }
                var s = NightSession.Instance;
                float blizzard = Weather.Storm;
                // darkness by the sun under the horizon (and a bit more under a closed cloud deck)
                float alt = SkyDome.SunAlt;
                float night = Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(-1.5f, -13f, alt));
                night = Mathf.Clamp01(night + .08f * SkyDome.CloudCover * night);
                if (s == null) night = 0f;
                // site views are for looking at things: keep them readable
                if (WorldDressing.ViewIndex >= 0 && !WorldDressing.ViewKeepsDark) night = Mathf.Min(night, .35f);
                Darkness = Mathf.MoveTowards(Darkness, night, Time.deltaTime * .5f);
                float d = Darkness;

                // fog takes the colour of the horizon, so the far forest melts into the sky; in a blizzard it is the grey wall of snow
                RenderSettings.fogColor = SkyDome.Horizon;
                // clear dusk: long views; night: the dark eats everything past ~60 m; blizzard gusts: a few metres
                float fog = s == null ? .0013f : Mathf.Lerp(.003f, .016f, d);
                fog = Mathf.Lerp(fog, Mathf.Lerp(.05f, .12f, Weather.Gust), blizzard);
                RenderSettings.fogDensity = fog;
                // ambient: the sky's own light, warmed by the afterglow while it lasts, greened a little by an aurora
                var glow = SkyDome.Glow * .12f * (1f - d);
                var aur = new Color(0f, .03f, .015f) * SkyDome.Aurora * (1f - SkyDome.CloudCover * .7f);
                RenderSettings.ambientSkyColor = Color.Lerp(DuskAmbSky, NightAmbSky, d) + glow + aur;
                RenderSettings.ambientEquatorColor = Color.Lerp(DuskAmbEq, NightAmbEq, d) + glow * 1.4f + aur;
                RenderSettings.ambientGroundColor = Color.Lerp(DuskAmbGround, NightAmbGround, d);
                var cam = Camera.main; if (cam != null) { cam.clearFlags = CameraClearFlags.SolidColor; cam.backgroundColor = SkyDome.Horizon; }
                if (sun != null)
                {
                    // above the horizon: the low sun itself; below: the afterglow as a soft light from the sun's side, gone by nautical dusk
                    var dir = SkyDome.SunDir;
                    var flat = new Vector3(dir.x, 0, dir.z).normalized;
                    float up = Mathf.Max(alt, 7f) * Mathf.Deg2Rad;
                    var from = (flat * Mathf.Cos(up) + Vector3.up * Mathf.Sin(up)).normalized;
                    sun.transform.rotation = Quaternion.LookRotation(-from);
                    float direct = Mathf.InverseLerp(-.5f, 3f, alt);
                    float after = Mathf.InverseLerp(-11f, -1f, alt) * .45f * (1f - SkyDome.CloudCover * .5f);
                    sun.intensity = Mathf.Max(direct * 1.3f, after) * (1f - blizzard * .6f);
                    sun.color = direct > .01f ? new Color(1f, .78f, .6f) : Color.Lerp(new Color(.55f, .6f, .85f), new Color(.95f, .6f, .5f), Mathf.InverseLerp(-8f, -1f, alt));
                    sun.shadows = direct > .01f ? LightShadows.Soft : LightShadows.None;
                    sun.enabled = sun.intensity > .005f;
                }
                if (moonLight != null)
                {
                    // the thin waning moon low in the south-east before dawn: faint, blue, long soft shadows
                    float m = s == null ? 0f : Mathf.InverseLerp(0f, 8f, SkyDome.MoonAlt) * SkyDome.MoonLit * (1f - SkyDome.CloudCover * .8f) * (1f - blizzard);
                    var md = SkyDome.MoonDir;
                    var mflat = new Vector3(md.x, 0, md.z).normalized;
                    float mup = Mathf.Max(SkyDome.MoonAlt, 4f) * Mathf.Deg2Rad;
                    moonLight.transform.rotation = Quaternion.LookRotation(-(mflat * Mathf.Cos(mup) + Vector3.up * Mathf.Sin(mup)));
                    moonLight.intensity = m * .22f;
                    moonLight.enabled = moonLight.intensity > .003f;
                }
                float fire = s != null ? s.FireRemaining.Value : 0f;
                if (ember != null) ember.enabled = fire > 0f;
                if (flames != null) { var fe = flames.emission; fe.enabled = fire > 0f; }
                if (fireSmoke != null) { var em = fireSmoke.emission; em.enabled = fire > 0f; }
                if (fireLight != null) fireLight.intensity = fire > 0f ? (3.2f + .8f * Mathf.PerlinNoise(Time.time * 6f, 0f)) * Mathf.Lerp(1f, 1.4f, d) : 0f;
                if (film != null) film.Set(s != null ? d : 0f, blizzard);
                // the night fog hides everything past ~150 m (a blizzard: far less): don't draw trees nobody can see
                var terrain = Terrain.activeTerrain;
                if (terrain != null)
                {
                    float far = s == null ? 1400f : Mathf.Lerp(Mathf.Lerp(1400f, 260f, d), 120f, blizzard);
                    if (Mathf.Abs(terrain.treeDistance - far) > 10f) terrain.treeDistance = far;
                }
            }
        }
    }
}
