using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using UnityEngine;
using UnityEngine.EventSystems;
using Height1079.Core;

namespace Height1079.Runtime
{
    /// <summary>Builds the whole scene from code when the game starts: slope, camp, lighting, network manager, UI.
    /// Prefabs (player, night session) are generated by the editor bootstrap into Assets/Resources.</summary>
    public static class Bootstrap
    {
        public static float[] Dem { get; private set; }
        public static string PlayerName = "Путник";
        public static bool AutoKindle;
        /// <summary>Set by the optional Steam assembly; null when the game runs with plain Unity Transport.</summary>
        public static ILobbyProvider Lobby;
        public static HudController Hud { get; private set; }
        public static HikerController LocalHiker
        {
            get
            {
                var nm = NetworkManager.Singleton;
                if (nm == null || nm.LocalClient == null || nm.LocalClient.PlayerObject == null) return null;
                return nm.LocalClient.PlayerObject.GetComponent<HikerController>();
            }
        }

        static Light sun;
        static Light fireLight;
        static Renderer ember;
        static NetworkManager network;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Boot()
        {
            if (Object.FindFirstObjectByType<NetworkManager>() != null) return;
            Application.targetFrameRate = 120;
            Dem = TerrainBuilder.LoadDem();
            BuildWorld();
            BuildNetwork();
            Hud = HudController.Create();
            Ambience.Create();
            var driver = new GameObject("Atmosphere", typeof(Atmosphere));
            Object.DontDestroyOnLoad(driver);
        }

        static Material Flat(Color c)
        {
            var template = Resources.Load<Material>("Flat"); // created by ProjectSetup so the shader ships in builds
            var m = template != null ? new Material(template) { color = c } : new Material(Shader.Find("Standard")) { color = c };
            m.SetFloat("_Glossiness", .05f); m.SetFloat("_Metallic", 0f);
            return m;
        }

        static void BuildWorld()
        {
            var snow = Flat(new Color(.886f, .91f, .93f));
            TerrainBuilder.Build(Dem, snow);

            var sunGo = new GameObject("Sun", typeof(Light));
            sun = sunGo.GetComponent<Light>();
            sun.type = LightType.Directional; sun.color = new Color(1f, .94f, .84f); sun.intensity = 1.6f; sun.shadows = LightShadows.Soft;
            sunGo.transform.rotation = Quaternion.Euler(38f, -110f, 0f);
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(.89f, .94f, 1f); RenderSettings.ambientEquatorColor = new Color(.6f, .66f, .7f); RenderSettings.ambientGroundColor = new Color(.35f, .38f, .4f);
            RenderSettings.fog = true; RenderSettings.fogMode = FogMode.ExponentialSquared; RenderSettings.fogDensity = .0013f; RenderSettings.fogColor = new Color(.68f, .74f, .78f);

            // Fictional camp: logs, ember, fire light.
            var camp = new GameObject("Camp");
            float cx = WorldData.Camp.x, cz = WorldData.Camp.z, cy = TerrainBuilder.Height(Dem, cx, cz);
            camp.transform.position = new Vector3(cx, cy, cz);
            var wood = Flat(new Color(.32f, .27f, .23f));
            for (int i = 0; i < 5; i++)
            {
                var log = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                log.name = "Log"; log.transform.SetParent(camp.transform, false);
                log.transform.localPosition = new Vector3(0, .12f, 0); log.transform.localScale = new Vector3(.22f, .6f, .22f);
                log.transform.localRotation = Quaternion.Euler(0, i * 36f, 90f);
                log.GetComponent<Renderer>().sharedMaterial = wood;
            }
            var emberGo = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            emberGo.name = "Ember"; emberGo.transform.SetParent(camp.transform, false); emberGo.transform.localPosition = new Vector3(0, .5f, 0); emberGo.transform.localScale = new Vector3(.6f, .9f, .6f);
            Object.Destroy(emberGo.GetComponent<Collider>());
            var emberMat = Flat(new Color(1f, .71f, .3f)); emberMat.EnableKeyword("_EMISSION"); emberMat.SetColor("_EmissionColor", new Color(1f, .55f, .2f) * 2.5f);
            ember = emberGo.GetComponent<Renderer>(); ember.sharedMaterial = emberMat; ember.enabled = false;
            var lightGo = new GameObject("FireLight", typeof(Light)); lightGo.transform.SetParent(camp.transform, false); lightGo.transform.localPosition = new Vector3(0, 1.1f, 0);
            fireLight = lightGo.GetComponent<Light>(); fireLight.type = LightType.Point; fireLight.color = new Color(1f, .64f, .28f); fireLight.range = 24f; fireLight.intensity = 0f; fireLight.shadows = LightShadows.Soft;

            // Upper shelter (tent) and archive markers.
            var tent = GameObject.CreatePrimitive(PrimitiveType.Cube);
            tent.name = "Tent"; tent.transform.position = new Vector3(WorldData.Tent.X, TerrainBuilder.Height(Dem, WorldData.Tent.X, WorldData.Tent.Z) + .9f, WorldData.Tent.Z);
            tent.transform.localScale = new Vector3(3.6f, 1.8f, 5.2f); tent.transform.rotation = Quaternion.Euler(0, 0, 45f);
            tent.GetComponent<Renderer>().sharedMaterial = Flat(new Color(.5f, .49f, .38f));
            var post = Flat(new Color(.32f, .27f, .23f));
            foreach (var p in WorldData.Pois)
            {
                if (p.Id == "tent") continue;
                var pole = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                pole.name = "Marker " + p.Id; pole.transform.position = new Vector3(p.X, TerrainBuilder.Height(Dem, p.X, p.Z) + .75f, p.Z);
                pole.transform.localScale = new Vector3(.12f, .75f, .12f); pole.GetComponent<Renderer>().sharedMaterial = post;
                var sign = GameObject.CreatePrimitive(PrimitiveType.Cube);
                sign.transform.SetParent(pole.transform, false); sign.transform.localPosition = new Vector3(0, 1f, 0); sign.transform.localScale = new Vector3(4f, .35f, .5f);
                sign.GetComponent<Renderer>().sharedMaterial = Flat(p.Source == "field" ? new Color(.53f, .73f, .73f) : new Color(.84f, .68f, .38f));
            }

            // Tree line: instanced cones below 755 m, seeded like the browser prototype.
            var trunkMat = Flat(new Color(.32f, .27f, .23f)); var leafMat = Flat(new Color(.19f, .27f, .25f));
            uint seed = 1959; float Rnd() { seed = seed * 1664525u + 1013904223u; return seed / 4294967296f; }
            var forest = new GameObject("Forest");
            int n = 0;
            for (int i = 0; i < 6000 && n < 900; i++)
            {
                float x = (Rnd() - .5f) * ((float)WorldData.Size - 20f), z = (Rnd() - .5f) * ((float)WorldData.Size - 20f);
                float h = WorldData.Sample(Dem, x, z);
                if (h > 755f || Rnd() > (755f - h) / 70f || WorldData.CreekDistance(x, z) < 5f) continue;
                float height = 3f + Rnd() * 9f, y = TerrainBuilder.Height(Dem, x, z);
                var tree = new GameObject("Tree"); tree.transform.SetParent(forest.transform, false); tree.transform.position = new Vector3(x, y, z);
                var trunk = GameObject.CreatePrimitive(PrimitiveType.Cylinder); trunk.transform.SetParent(tree.transform, false);
                trunk.transform.localPosition = new Vector3(0, height * .5f, 0); trunk.transform.localScale = new Vector3(.3f, height * .5f, .3f); trunk.GetComponent<Renderer>().sharedMaterial = trunkMat;
                // trunks keep their colliders and block movement; crowns do not
                for (int j = 0; j < 4; j++)
                {
                    var crown = GameObject.CreatePrimitive(PrimitiveType.Cylinder); crown.transform.SetParent(tree.transform, false);
                    Object.Destroy(crown.GetComponent<Collider>());
                    float w = (1f - j * .18f) * height * .28f;
                    crown.transform.localPosition = new Vector3(0, height * (.42f + j * .14f), 0); crown.transform.localScale = new Vector3(w, height * .16f, w);
                    crown.GetComponent<Renderer>().sharedMaterial = leafMat;
                }
                n++;
            }
        }

        static void BuildNetwork()
        {
            var go = new GameObject("NetworkManager", typeof(NetworkManager), typeof(UnityTransport));
            Object.DontDestroyOnLoad(go);
            network = go.GetComponent<NetworkManager>();
            var transport = go.GetComponent<UnityTransport>();
            network.NetworkConfig = new NetworkConfig { NetworkTransport = transport, ConnectionApproval = false, EnableSceneManagement = false, TickRate = 30 };
            var player = Resources.Load<GameObject>("Hiker");
            var session = Resources.Load<GameObject>("NightSession");
            if (player == null || session == null) { Debug.LogError("Missing Resources/Hiker or Resources/NightSession prefab — open the project in the editor once (menu 1079 → Generate prefabs)."); return; }
            network.NetworkConfig.PlayerPrefab = player;
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = player });
            network.NetworkConfig.Prefabs.Add(new NetworkPrefab { Prefab = session });
            network.OnServerStarted += () => Object.Instantiate(session).GetComponent<NetworkObject>().Spawn();
            network.OnClientDisconnectCallback += id => { if (id == network.LocalClientId || !network.IsListening) OnLeft(); };
        }

        public static void Host(string name)
        {
            PlayerName = string.IsNullOrWhiteSpace(name) ? "Путник" : name.Trim();
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData("0.0.0.0", 7777, "0.0.0.0");
            if (network.StartHost()) Hud.ShowMenu(false); else Hud.SetStatus("Не удалось открыть порт 7777.");
        }

        public static void Join(string name, string address)
        {
            PlayerName = string.IsNullOrWhiteSpace(name) ? "Путник" : name.Trim();
            var transport = network.GetComponent<UnityTransport>(); network.NetworkConfig.NetworkTransport = transport;
            transport.SetConnectionData(string.IsNullOrWhiteSpace(address) ? "127.0.0.1" : address.Trim(), 7777);
            if (network.StartClient()) { Hud.ShowMenu(false); Hud.SetStatus("Подключаемся…"); } else Hud.SetStatus("Не удалось подключиться.");
        }

        public static void Leave()
        {
            Lobby?.Leave();
            if (network.IsListening) network.Shutdown();
            OnLeft();
        }

        static void OnLeft()
        {
            AutoKindle = false;
            Cursor.lockState = CursorLockMode.None; Cursor.visible = true;
            if (Hud != null) { Hud.ShowMenu(true); Hud.SetStatus("Ночь закончена. Можно начать новую."); }
        }

        public static bool PointerOverUi() => EventSystem.current != null && EventSystem.current.IsPointerOverGameObject();

        /// <summary>Per-frame environment: sky darkens with the night, fog thickens in storms, the fire glows while it burns.</summary>
        sealed class Atmosphere : MonoBehaviour
        {
            static readonly Color Dusk = new Color(.62f, .67f, .71f), Night = new Color(.1f, .17f, .25f);
            void Update()
            {
                var s = NightSession.Instance;
                float night = s != null ? Mathf.Clamp01(s.Elapsed.Value / 220f) : 0f;
                bool storm = s != null && s.Storm.Value;
                var sky = Color.Lerp(Dusk, Night, night);
                RenderSettings.fogColor = sky; RenderSettings.fogDensity = storm ? .045f : s != null ? .003f : .0013f;
                var cam = Camera.main; if (cam != null) { cam.clearFlags = CameraClearFlags.SolidColor; cam.backgroundColor = sky; }
                if (sun != null) sun.intensity = 1.6f - night * 1.3f;
                float fire = s != null ? s.FireRemaining.Value : 0f;
                if (ember != null) { ember.enabled = fire > 0f; ember.transform.localScale = new Vector3(.6f, .9f, .6f) * (1f + Mathf.Sin(Time.time * 13f) * .12f); }
                if (fireLight != null) fireLight.intensity = fire > 0f ? 3.5f + Mathf.Sin(Time.time * 17f) * .5f : 0f;
            }
        }
    }
}
